name: npm-enforced-engines
on: push
jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
